<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	//http://stackoverflow.com/questions/8146461/custom-repository-class-in-symfony2
	
	public function getArticles(){
		$articles = array(
				array('titre'=>"article 1", 'contenu'=>"blablabla"),
				array('titre'=>"article 2", 'contenu'=>"nanani"),
				array('titre'=>"article 3", 'contenu'=>"lalala")
				 
		);
		return $articles;
	}
}
